### Axis in NumPy

#### 0 for column | 1 for row

In [1]:
import numpy as np

In [2]:
ar1 = np.array([[1,2,3],[4,5,6]])
ar1

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
ar1.sum(axis=0) # sum in columns

array([5, 7, 9])

In [4]:
ar1.sum(axis=1) # sum in columns

array([ 6, 15])

#### Dot Product

In [5]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
b = np.array([[4,9,6],[7,8,12]])
print(b)

[[1 2 3]
 [4 5 6]]
[[ 4  9  6]
 [ 7  8 12]]


In [6]:
a.dot(b) # throws error bcz 2*3 matrix cannot multiply with 2*3 matrix so we have to transpose one matrix

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [7]:
a.dot(b.transpose())

array([[ 40,  59],
       [ 97, 140]])

In [8]:
len(dir(np))

596

In [9]:
np.dot(a,b.transpose())

array([[ 40,  59],
       [ 97, 140]])

In [11]:
np.cross(a,b)

array([[-15,   6,   1],
       [ 12,  -6,  -3]])

#### Sorting

In [14]:
a = np.array([[1,12,3,24,15,6],[4,9,6,7,38,12]])

np.sort(a)

array([[ 1,  3,  6, 12, 15, 24],
       [ 4,  6,  7,  9, 12, 38]])

In [15]:
np.sort(a, axis=0) # sort elements in columns

array([[ 1,  9,  3,  7, 15,  6],
       [ 4, 12,  6, 24, 38, 12]])

In [18]:
x = np.sort(a, axis=0, kind='mergesort')  # specify what sorting algorithm you want to use
print('mergesort',x)
y = np.sort(a, axis=0, kind='quicksort')
print('quicksort',y)
z = np.sort(a, axis=0, kind='heapsort')
print('heapsort',z)

mergesort [[ 1  9  3  7 15  6]
 [ 4 12  6 24 38 12]]
quicksort [[ 1  9  3  7 15  6]
 [ 4 12  6 24 38 12]]
heapsort [[ 1  9  3  7 15  6]
 [ 4 12  6 24 38 12]]


#### Reshape and arange()

In [20]:
mat = np.arange(18)
mat.shape

(18,)

In [21]:
x = mat.reshape(3,6)
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [22]:
x = mat.reshape(9,2)
x

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17]])

In [ ]:
#### argsort, argmax and argmin