In [2]:
import numpy as np

In [3]:
print(2)

2


In [5]:
arr = np.arange(1000000)

In [6]:
lst  = list(arr)

In [10]:
%time for i in range(10): [i*3 for i in lst]

CPU times: total: 1.02 s
Wall time: 1.9 s


In [11]:
%time for i in range(10): arr = arr*3

CPU times: total: 15.6 ms
Wall time: 33.2 ms


In [12]:
np.array([1,5,8,9,7,4,5,6,3])

array([1, 5, 8, 9, 7, 4, 5, 6, 3])

### Numpy ndArrays

In [14]:
array1 = np.array([[1,5,2,9,45],[1,9,7,4,2]])

In [15]:
print(array1)
print(type(array1))

[[ 1  5  2  9 45]
 [ 1  9  7  4  2]]
<class 'numpy.ndarray'>


In [18]:
array1.shape

(2, 5)

In [19]:
array1.dtype

dtype('int32')

In [21]:
array1 = np.array([[1,5,2,9,45],[1,9,7,4,2]], 'int64')

In [22]:
array1.dtype

dtype('int64')

In [23]:
array1 = np.array([[1,5,2,0.89,45],[1,0.49,7,4.65,2]], 'float64')

In [24]:
array1.shape

(2, 5)

In [25]:
array1.dtype

dtype('float64')

### Empty arrays

In [26]:
arr = np.zeros(4)
arr

array([0., 0., 0., 0.])

In [27]:
arr = np.zeros((4,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [28]:
arr = np.zeros((4,6,9))
arr

array([[[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.,

In [29]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [30]:
np.ones(6).dtype

dtype('float64')

In [31]:
np.empty((4,6))  # it allocate memory to array but it is not mendatory that the values always 0 it can be garbage value 

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [32]:
array1 = np.array([[1,5,2,9,45],[1,9,7,4,2]], 'int64')

# element wise multipliocation

array1 * array1

array([[   1,   25,    4,   81, 2025],
       [   1,   81,   49,   16,    4]], dtype=int64)

In [33]:
array1 + array1

array([[ 2, 10,  4, 18, 90],
       [ 2, 18, 14,  8,  4]], dtype=int64)

In [34]:
array1 / array1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [35]:
array1 ** array1

array([[                  1,                3125,                   4,
                  387420489, 2604998672350111773],
       [                  1,           387420489,              823543,
                        256,                   4]], dtype=int64)

In [36]:
array1 - array1

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int64)

In [37]:
1 / array1

array([[1.        , 0.2       , 0.5       , 0.11111111, 0.02222222],
       [1.        , 0.11111111, 0.14285714, 0.25      , 0.5       ]])

### Slicing in NumPy

In [56]:
array1 = np.array([1,5,2,9,4,3,8])
print(array1)

arr = array1[4:6]  # it gives a view of array (point to array) not a copy
print(arr)
arr[0] = 10
print(array1)

[1 5 2 9 4 3 8]
[4 3]
[ 1  5  2  9 10  3  8]


In [57]:
array1 = np.array([1,5,2,9,4,3,8])
print(array1)

arr = array1[4:6].copy()  # create a copy
print(arr)
arr[0] = 10
print(array1)

[1 5 2 9 4 3 8]
[4 3]
[1 5 2 9 4 3 8]
