In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [2]:
one_hot("amazing restaurant",50)

[43, 16]

In [3]:
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[15, 2], [7, 4], [1, 28], [24, 28, 18], [29, 12, 6], [12, 2], [18, 12, 22], [25, 18], [25, 11], [5, 28]]


In [6]:
max_length = 3
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[15  2  0]
 [ 7  4  0]
 [ 1 28  0]
 [24 28 18]
 [29 12  6]
 [12  2  0]
 [18 12 22]
 [25 18  0]
 [25 11  0]
 [ 5 28  0]]


In [7]:
embeded_vector_size = 5

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length,name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [8]:
X = padded_reviews
y = sentiment

In [9]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary())

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 3, 5)              150       
                                                                 
 flatten_1 (Flatten)         (None, 15)                0         
                                                                 
 dense_1 (Dense)             (None, 1)                 16        
                                                                 
Total params: 166 (664.00 Byte)
Trainable params: 166 (664.00 Byte)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________
None


In [10]:
model.fit(X, y, epochs=50, verbose=0)

In [11]:
# evaluate the model
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 [==============================] - 0s 249ms/step - loss: 0.6061 - accuracy: 1.0000


1.0

In [12]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [13]:
weights[13]

array([-0.02667097,  0.01382663, -0.02995602,  0.03335576,  0.04940529],
      dtype=float32)

In [14]:
weights[4]

array([-0.02513758, -0.00793252, -0.0079597 ,  0.0601285 ,  0.01468487],
      dtype=float32)

In [15]:
weights[16]

array([-0.01772543, -0.00897928, -0.03540636, -0.03980943, -0.0002544 ],
      dtype=float32)