### Axis in NumPy

#### 0 for column | 1 for row

In [5]:
import numpy as np

In [8]:
ar1 = np.array([[1,2,3],[4,5,6]])
print(ar1)
ar1.sum()

[[1 2 3]
 [4 5 6]]


21

In [3]:
ar1.sum(axis=0) # sum in columns

array([5, 7, 9])

In [4]:
ar1.sum(axis=1) # sum in columns

array([ 6, 15])

#### Dot Product

In [5]:
a = np.array([[1,2,3],[4,5,6]])
print(a)
b = np.array([[4,9,6],[7,8,12]])
print(b)

[[1 2 3]
 [4 5 6]]
[[ 4  9  6]
 [ 7  8 12]]


In [6]:
a.dot(b) # throws error bcz 2*3 matrix cannot multiply with 2*3 matrix so we have to transpose one matrix

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [7]:
a.dot(b.transpose())

array([[ 40,  59],
       [ 97, 140]])

In [8]:
len(dir(np))

596

In [9]:
np.dot(a,b.transpose())

array([[ 40,  59],
       [ 97, 140]])

In [10]:
np.cross(a,b)

array([[-15,   6,   1],
       [ 12,  -6,  -3]])

#### Sorting

In [11]:
a = np.array([[1,12,3,24,15,6],[4,9,6,7,38,12]])

np.sort(a)

array([[ 1,  3,  6, 12, 15, 24],
       [ 4,  6,  7,  9, 12, 38]])

In [12]:
np.sort(a, axis=0) # sort elements in columns

array([[ 1,  9,  3,  7, 15,  6],
       [ 4, 12,  6, 24, 38, 12]])

In [13]:
x = np.sort(a, axis=0, kind='mergesort')  # specify what sorting algorithm you want to use
print('mergesort',x)
y = np.sort(a, axis=0, kind='quicksort')
print('quicksort',y)
z = np.sort(a, axis=0, kind='heapsort')
print('heapsort',z)

mergesort [[ 1  9  3  7 15  6]
 [ 4 12  6 24 38 12]]
quicksort [[ 1  9  3  7 15  6]
 [ 4 12  6 24 38 12]]
heapsort [[ 1  9  3  7 15  6]
 [ 4 12  6 24 38 12]]


#### Reshape and arange()

In [9]:
mat = np.arange(18)
print(mat)
mat.shape

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


(18,)

In [10]:
x = mat.reshape(3,6)
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [11]:
x = mat.reshape(2,8)
x

ValueError: cannot reshape array of size 18 into shape (2,8)

In [16]:
x = mat.reshape(9,2)
x

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15],
       [16, 17]])

### argsort, argmax and argmin

In [17]:
# argsort give the index of values which can sort the array in ascending order

mat = np.array([4,5,8,1,2,7,12,36,9,8,45,1,25,21])
mat.shape

(14,)

In [18]:
np.argsort(mat)

array([ 3, 11,  4,  0,  1,  5,  2,  9,  8,  6, 13, 12,  7, 10],
      dtype=int64)

In [19]:
np.argmax(mat)

10

In [20]:
np.argmin(mat)

3

### Slicing in numpy

In [13]:
a = np.array([6,  5,  4, 6,  5,  4])

print(a)

[6 5 4 6 5 4]


In [14]:
a[np.newaxis,:]  # new axis increase the dimension of numpy array

array([[6, 5, 4, 6, 5, 4]])

In [15]:
print(a[:])
print(a[1:4])
print(a[np.newaxis,1:5])

[6 5 4 6 5 4]
[5 4 6]
[[5 4 6 5]]


In [28]:
x = np.array([[ 6,  5,  4, 6,  5,  4],
       [ 7,  6,  5, 7,  6,  5],
       [ 8,  7,  6, 8,  7,  6],
       [ 9,  8,  7, 9,  8,  7],
       [10,  9,  8, 10,  9,  8]])

print(x)

[[ 6  5  4  6  5  4]
 [ 7  6  5  7  6  5]
 [ 8  7  6  8  7  6]
 [ 9  8  7  9  8  7]
 [10  9  8 10  9  8]]


In [29]:
x[np.newaxis,:,1:3]

array([[[5, 4],
        [6, 5],
        [7, 6],
        [8, 7],
        [9, 8]]])